name: Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run Linter
        run: |
        npm install
        npm run lint
